name: ItemBan
version: 1.0.0
main: bladesmp.bladesmp.ItemBan
api-version: 1.21
folia-supported: true
author: YourName
description: Ein Plugin das Items im Combat sperrt und komplett verbieten kann
website: https://github.com/MrK4mo/ItemBan

dependencies:
  server:
    paper:
      load: BEFORE
      required: false

# Soft-Dependencies (optional)
softdepend: [WorldGuard]

permissions:
  itemban.admin:
    description: Erlaubt die Verwaltung des ItemBan Plugins
    default: op
  itemban.bypass.combat:
    description: Umgeht Combat Item-Beschränkungen
    default: false
  itemban.bypass.banned:
    description: Umgeht komplett verbotene Items
    default: false